# -*- coding: utf-8 -*-
"""Tahap 2 Case Representation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kzcb3HMjrmrwQvlEs2LYfZSs03xBlPjP

# **Tahap 2 – Case Representation**

---
"""

import os
import pandas as pd

# Path input
csv_path = "/content/drive/MyDrive/Penalaran Komputer/UAS/CSV/putusan_ma__2025-06-19.csv"
ocr_folder = "/content/drive/MyDrive/Penalaran Komputer/UAS/Data/raw"
output_csv = "/content/drive/MyDrive/Penalaran Komputer/UAS/Data/processed/cases.csv"

# Load data CSV scraping
df = pd.read_csv(csv_path)
df["nomor"] = df["nomor"].astype(str).str.strip()

# Siapkan list hasil
case_rows = []

# Loop semua OCR file
ocr_files = [f for f in os.listdir(ocr_folder) if f.endswith(".txt")]

for idx, fname in enumerate(sorted(ocr_files)):
    case_id = idx + 1
    with open(os.path.join(ocr_folder, fname), "r", encoding="utf-8") as f:
        text = f.read()

    # Cari baris yang cocok dengan nama file
    match_row = df[df["file_name_pdf"].str.contains(fname.replace(".txt", ""), na=False)]

    if match_row.empty:
        continue

    row = match_row.iloc[0]
    nomor = row.get("nomor", "")
    tanggal = row.get("tanggal_register", "")
    jenis = row.get("klasifikasi", "")
    pasal = row.get("kata_kunci", "")
    pihak = row.get("pihak", row.get("lembaga_peradilan", "Tidak diketahui"))
    fakta = row.get("catatan_amar", "")  # asumsikan ringkasan fakta dari sini
    amar = row.get("amar", "")

    # Feature Engineering
    length = len(text.split())

    # Gabungan
    text_full = f"{nomor} {tanggal} {fakta} {pasal} {pihak}"

    case_rows.append({
        "case_id": case_id,
        "no_perkara": nomor,
        "tanggal": tanggal,
        "jenis_perkara": jenis,
        "ringkasan_fakta": fakta,
        "pasal": pasal,
        "pihak": pihak,
        "amar": amar,
        "text_full": text_full,
        "length": length
    })

# Simpan ke CSV
df_case = pd.DataFrame(case_rows)
df_case.to_csv(output_csv, index=False)
print(f"✅ Disimpan: {output_csv}")